version: 2.1

orbs:
  codacy: codacy/base@2.0.1
  codacy_plugins_test: codacy/plugins-test@0.7.1

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - codacy/checkout_and_version
      - codacy/sbt:
          name: check_format_and_test
          cmd: |
            sbt "set scalafmtUseIvy in ThisBuild := false;
                 scalafmt::test;
                 test:scalafmt::test;
                 sbt:scalafmt::test;
                 test"
          requires:
            - codacy/checkout_and_version
      - codacy/sbt:
          name: publish_docker_local
          cmd: |
            sbt "set name := \"$CIRCLE_PROJECT_REPONAME\";
                 set version in Docker := \"latest\";
                 docker:publishLocal"
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          requires:
            - check_format_and_test
      - codacy_plugins_test/run:
          name: plugins_test
          run_multiple_tests: true
          requires:
            - publish_docker_local
      - codacy/shell:
          name: publish_dockerhub
          cmd: |
            docker load --input docker-image.tar
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME:latest
            docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)
            docker push codacy/$CIRCLE_PROJECT_REPONAME
          filters:
            branches:
              only: master
          requires:
            - publish_docker_local
            - plugins_test
      - codacy/tag_version:
          context: CodacyAWS
          requires:
            - publish_dockerhub
